### ISSUE TITLE
signingscript is stuck on old docker images

### ISSUE THREAD

**Issue by bhearsum** [escapewindow/scriptworker-scripts#415]
We pinned to `python:3.8.10` in https://github.com/mozilla-releng/scriptworker-scripts/commit/4626000ccc5e264c69b6f5f06f67a7ed6362be14 due to osslsigncode bustage. Once `winsign` supports the newer osslsigncode version (tracked in https://github.com/mozilla-releng/winsign/issues/24), we should be able to unpin this.

**Comment by jmaher** [comment]
this is resolved now, we are on python:3.9.7 and winsign uses osslsigncode 2.1 (compatible with 2.2 as well)

**Comment by escapewindow** [comment]
We use `--untrusted`, which we may have to bump to `--TSA-CAfile` in winsign when we want to use osslsigncode 2.2: https://github.com/mtrojnar/osslsigncode/releases/tag/2.2
