### ISSUE TITLE
python 3.9 support

### ISSUE THREAD

**Issue by escapewindow** [escapewindow/scriptworker-scripts#424]
This is probably:

- add py3.9 to the matrix of requirements files we create via `pin.sh`
  - when we do this, it may be worthwhile to either add the `pyXX` to all the files, or see if we can just create one set, since we seem to be adding a version marker to `importlib-metadata`
- add py3.9 to the matrix of python versions we test in tox.ini
- this probably means python 3.9 docker-image and k8s-image tasks as well?
- look at whether/when we can drop py37 support. This probably won't be for a while. Looks like it will be supported until [2023](https://www.python.org/dev/peps/pep-0537/#lifespan).
- potentially look at adding py3.10 to the matrix as well, since it was [released this month](https://www.python.org/dev/peps/pep-0619/#release-schedule).

We're already switching to py39 in #423, so we probably want this sooner rather than later.

**Comment by jmaher** [comment]
I have a PR up here: https://github.com/mozilla-releng/scriptworker-scripts/pull/428

**Comment by jmaher** [comment]
rolled out signingscript today, all caught up!
