### ISSUE TITLE
[pushmsixscript] package not updated in new submissions

### ISSUE THREAD

**Issue by gbrownmozilla** [escapewindow/scriptworker-scripts#474]
pushmsixscript is successfully creating new submissions for the Microsoft Store, but the new submission seems to re-use the package from the previous submission: The new msix files that we upload seem to disappear, and the new submission keeps serving up the old msix files.

**Comment by gbrownmozilla** [comment]
pushmsixscript uses the REST API documented at 
https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-app-submissions
and uses the python examples for inspiration:
https://docs.microsoft.com/en-us/windows/uwp/monetize/python-code-examples-for-the-windows-store-submission-api

Our application package currently consists of two msix files, one 32-bit and one 64-bit. pushmsixscript creates and updates the submission, then uploads each of the two msix files to the fileUploadUrl; each upload receives a 201 response code and no response body. pushmsixscript proceeds to commit the submission and monitors the commit status, typically seeing the status proceed from CommitStarted to PreProcessing. In the Partner Center, we can see the new submission and certification begins. However, the Package information for the new submission continues to reflect the original package -- not the new files uploaded.

**Comment by gbrownmozilla** [comment]
https://docs.microsoft.com/en-us/windows/uwp/monetize/python-code-examples-for-the-windows-store-submission-api#create-app-submission states:
`# Upload images and packages in a zip file. Note that large file might need to be handled differently`
We are only interested in updating our app, with the 2 msix files. Should we put the msix files in a zip file and upload the zip? I've tried that but the upload consistently fails: "Connection reset by peer". Might that be related to the file size (275 MB)?

**Comment by gbrownmozilla** [comment]
I also wonder whether the content of the submission request used to update the submission is correct. Currently pushmsixscript basically uses the submission request data returned from the create submission call, and sends that back to update submission. Is that okay, or should the submission request data be modified somehow?

**Comment by Seann-Murdock** [comment]
Can you please provide a product id from one of your test runs so that I can take a look at the requests from the service side?

**Comment by gbrownmozilla** [comment]
I have been testing with Store ID / Application ID 9NFQ5K7N2T6C ("Firefox Nightly"):

Package/Identity/Name | Mozilla.64253760D188F
Package/Identity/Publisher | CN=082E9164-EE6C-4EC8-B62C-441FAE7BEFA1

**Comment by Seann-Murdock** [comment]
>I also wonder whether the content of the submission request used to update the submission is correct. 

This depends on how you are making your call to create the submission, If you are not providing a body and just creating a new submission based off the previous published one you will need to call the update submission API after creation to make your changes. 

If you provide a body to the submission creation API and that fully encompasses all the changes you want in your submission you shouldn't  need to call the update API and can go straight to commit (once you have uploaded the ZIP.)

About the zip file I do believe that the expectation is that both packages should be uploaded in a ZIP file to the file sas uri you get from creating the submission. I'm not sure why there is that comment you saw in the python examples as it isn't present in any other language. I don't see anything in the code that suggests an alternative for large files but I'm following up with the file service team to see if there is anything specific that needs to be handled differently. 

It may be the case that our instructions aren't the best way to upload large files in python but my python chops are a little rusty.  I've seen a lot of suggestions for this https://pypi.org/project/requests-toolbelt/ to help with chunking large file uploads.

**Comment by gbrownmozilla** [comment]
Thanks @Seann-Murdock 

I'm not sure I understand how requests-toolbelt would help. Would I use the MultipartEncoder? But then I would be multipart-encoding just one file, right? I wouldn't expect that to make a difference...but I can give it a try.

**Comment by gbrownmozilla** [comment]
I found I can successfully upload a zip file containing our two msix files if I shrink the size of the msix: I deleted files from our application to substantially reduce the size and the resulting zip uploaded fine. 275MB zip consistently fails; 172 MB zip seems to work.

**Comment by gbrownmozilla** [comment]
Regarding requests-toolbelt, I also noticed, on https://docs.python-requests.org/en/master/user/quickstart/, "In the event you are posting a very large file as a multipart/form-data request, you may want to stream the request. By default, requests does not support this, but there is a separate package which does - requests-toolbelt."

Does the Store accept multipart/form-data requests? I don't see that spelled out anywhere.

Anyway, I tried:
```
      with open("upload.zip", "rb") as f:
            m = MultipartEncoder(fields={'file': ('upload.zip', f, 'application/zip')})
            upload_headers = {"x-ms-blob-type": "BlockBlob", "Content-Type": m.content_type}
            response = requests.put(upload_url, data=m, headers=upload_headers, timeout=1800)
            response.raise_for_status()
```
That completes with a response code of 201, even with our 275MB zip...BUT the commit fails:

`{"status":"CommitFailed","statusDetails":{"errors":[{"code":"InvalidParameterValue","details":"We are not able to open file at 'https://ingestionpackagesprod1.blob.core.windows.net/ingestion/5fd4246b-33f1-49d4-8d29-1619738ba07c?sv=2018-03-28&sr=b&sig=u6sUKiIJPe5d79zIoWUvXYjRcqPoPz4QmEWyZSK8K70%3D&se=2022-03-04T22%3A50%3A56Z&sp=rwl'. Please make sure you upload the new packages and images in a zip archive to the file upload URL provided with the submission object."}],"warnings":[{"code":"SalesUnsupportedWarning","details":"The sales resource is no longer supported. To view or edit the sales data for this submission, use the Dev Center dashboard."}],"certificationReports":[]}}
`

@Seann-Murdock Can you see what happened on the server? Any other guidance?

**Comment by gbrownmozilla** [comment]
I also tried using requests_toolbelt.streaming_iterator, but that didn't help: It works for my 172MB zip, but fails for the real zip which is 275 MB (connection reset by peer).

**Comment by gbrownmozilla** [comment]
For completeness, I tried some more speculative experiments:
 - Create 2 zip files, each containing 1 msix file (about 135 MB each) and upload each zip via streaming_iterator during one submission; result: each upload receives a 201 response, but the commit fails: 'File 'target.store.up.1.msix' not found in archive."' and the Partner Center shows an in-progress submission with no changes to its packages.
 - Create 2 zip files, each containing 1 msix file (about 135 MB each) and upload them with one MultipartEncoder during one submission: after a few minutes, the upload fails, "connection reset by peer", and the in-progress submission has no changes to its packages.
 - Since there was some question about the robustness of python http operations, I re-wrote the upload in Java, based on the example at https://docs.microsoft.com/en-us/windows/uwp/monetize/java-code-examples-for-the-windows-store-submission-api. It behaves just the same as the (streaming_iterator) python version, successfully uploading smaller zip files but failing with our full 275 MB application zip:
```
Mar 11, 2022 3:37:14 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://ingestionpackagesprod1.blob.core.windows.net:443: Connection reset
Mar 11, 2022 3:37:14 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://ingestionpackagesprod1.blob.core.windows.net:443
Mar 11, 2022 3:39:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://ingestionpackagesprod1.blob.core.windows.net:443: Connection reset
Mar 11, 2022 3:39:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://ingestionpackagesprod1.blob.core.windows.net:443
Mar 11, 2022 3:41:28 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://ingestionpackagesprod1.blob.core.windows.net:443: Connection reset
Mar 11, 2022 3:41:28 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://ingestionpackagesprod1.blob.core.windows.net:443
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:319)
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1188)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
	at org.apache.http.entity.FileEntity.writeTo(FileEntity.java:113)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at IngestionServiceJavaSamples.UploadZipFile(IngestionServiceJavaSamples.java:42)
	at IngestionServiceJavaSamples.main(IngestionServiceJavaSamples.java:28)

```

It seems to me there must be some server-side bug/feature in the Store API limiting uploads to something like < 256 MB.

**Comment by gbrownmozilla** [comment]
I noticed a 256 MB limit ("Maximum blob size via single write operation (via Put Blob)" / "Version 2016-05-31 through version 2019-07-07") at https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob. But I don't know if that is applicable or relevant to the Store API.

**Comment by Seann-Murdock** [comment]
I've reached out to the storage team to confirm if there are any file size limits that are causing problems here.

For your previous tests trying to split the files into 2 separate zips is failing by design. On the store side when you upload two separate files you're essentially overwriting the first one with the second.

**Comment by prosser** [comment]
Can you upload manually using, e.g., [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/#overview)? If that works, but uploading from code does not, then there is a bug in the upload code.

**Comment by gbrownmozilla** [comment]
I was able to upload my full application zip to my own blob container in Azure Storage Explorer
![azure-screenshot](https://user-images.githubusercontent.com/4096201/158479559-04a9e21c-734e-4429-90b9-c8732346374e.png)
It took a very long time - over 8000 seconds! @prosser  Is this what you meant?

**Comment by gbrownmozilla** [comment]
My test files:
 - https://drive.google.com/file/d/1rtJakBVbKkZOxHBFgG-yJpOlA6GOg3LG/view?usp=sharing - the full, larger zip file that I cannot upload to the Store API.
 - https://drive.google.com/file/d/1aLqToQbd8xIUXyJE3-gTcYa0_F_ZG_b6/view?usp=sharing - the smaller zip file that uploads correctly.

**Comment by gbrownmozilla** [comment]
Amir reached out for additional help from Microsoft on March 30, but I have not seen any new guidance. I'm totally blocked here.

**Comment by escapewindow** [comment]
I'm curious if an aiohttp upload would help here, especially since we'd want to someday move pushmsix to aiohttp to match the other scriptworker scripts.

**Comment by gbrownmozilla** [comment]
Help...how? It seems unlikely that would get us unblocked and successfully upload: I've already tried an alternative implementation in Java (March 11) and it behaved identically.

For speed, I don't anticipate any improvement with async: The upload is 99% of the overall transaction time, and the upload is an http post of a single file -- there's nothing to do while the upload is in progress.

**Comment by Seann-Murdock** [comment]
I reached out to the file service team which owns the storage that you are attempting to upload your zip package to. The advice they've shared is to please use the python azure storage libraries for file upload.

For example here is how to create a blob storage client from the sas_url:


 # [START create_blob_client_sas_url]
        from azure.storage.blob import BlobClient

        sas_url = "https://account.blob.core.windows.net/container/blob-name?sv=2015-04-05&st=2015-04-29T22%3A18%3A26Z&se=2015-04-30T02%3A23%3A26Z&sr=b&sp=rw&sip=168.1.5.60-168.1.5.70&spr=https&sig=Z%2FRHIX5Xcg0Mq2rqI3OlWTjEg2tYkboXr1P9ZUXDtkk%3D"
        blob_client = BlobClient.from_blob_url(sas_url)
        # [END create_blob_client_sas_url]
        
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_authentication.py#L80

And here is how to upload the file content:
# [START upload_a_blob]
            # Upload content to block blob
            with open(SOURCE_FILE, "rb") as data:
                blob_client.upload_blob(data, blob_type="BlockBlob")
            # [END upload_a_blob]
            
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py#L68

**Comment by prosser** [comment]
I tested this approach against a blob account, and it successfully transmitted a 3 GB file:

```python
import io
import os
import time

from azure.storage.blob import BlobClient

sas_url = r'<redacted>'
source_file = '<redacted>'

file_size = os.path.getsize(source_file)
start_time = time.time()

def format_time(sec):
  mins = sec // 60
  sec = '%02d' % (sec % 60,)
  hours = int(mins // 60)
  mins = '%02d' % (int(mins % 60),)
  
  return f'{hours}:{mins}:{sec}'

def format_bps(bps):
  result = bps
  index = 0
  suffixes = ['bps', 'Kbps', 'Mbps', 'Gbps', 'Tbps'] # not likely to reach Tbps!

  while (result > 1000):
    result /= 1000
    index += 1

  if (index > len(suffixes)):
    index = len(suffixes) - 1
  return f'{round(result, 2)} {suffixes[index]}'

def print_progress(bytes_read):
  elapsed = time.time() - start_time
  bps = format_bps(bytes_read / elapsed * 8)
  read = '{:,}'.format(bytes_read)
  total = '{:,}'.format(file_size)
  print(f'\r{read} / {total} bytes transmitted ({bps}) ', end='', flush=True)

# 4 MB chunk size
chunk_size=4*1024*1024

blob_client = BlobClient.from_blob_url(sas_url)

if (blob_client.exists()):
  blob_client.delete_blob()

blob_client.create_append_blob()
bytes_read = 0
print_progress(bytes_read)

with open(source_file, 'rb') as file:
  fi = io.FileIO(file.fileno())
  stream = io.BufferedReader(fi)
  while True:
    read_data = stream.read(chunk_size)

    bytes_read += len(read_data)

    if not read_data:
      print('done')
      break
    blob_client.append_block(read_data)
    print_progress(bytes_read)

elapsed = format_time(time.time() - start_time)
print(f'\nUpload completed in {elapsed}')
```

Output was:
```shell
3,071,934,464 / 3,071,934,464 bytes transmitted (70.08 Mbps)

Upload completed in 0:05:50
```

**Comment by gbrownmozilla** [comment]
The python azure storage libraries do the trick - thanks!
