### ISSUE TITLE
ensure all beetmover gcs buckets are valid

### ISSUE THREAD

**Issue by bhearsum** [escapewindow/scriptworker-scripts#677]
In a staging release, I discovered that the `mozilla-releng-dep-partner` bucket we use for private partner build uploads is not valid, and causes tasks to fail. We should fix this, and ensure that all other buckets in [the configuration file](https://github.com/mozilla-releng/scriptworker-scripts/blob/master/beetmoverscript/docker.d/worker.yml) are valid. (We don't currently run any private partner repacks in production, so I'm concerned that these might be broken and we may not know it.)

**Comment by jcristau** [comment]
@bhearsum does #772 address this, or are there other buckets we're concerned about?

**Comment by bhearsum** [comment]
That's good, thanks! We can always file new issues if others come up.
